cache: npm
language: node_js
node_js:
  - "node"
env:
  global:
    CC_TEST_REPORTER_ID=3b099da1ac647288fcdf80707594d6db29c9284fc1766fcae225ba20afa96db4
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install                         # Install npm dependencies
script:
  - npm test                            # Frontend linting & specs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
